src/Badger/Bundle/GameBundle/Entity/BadgeInterface.php
<?php

namespace Badger\GameBundle\Entity;

use Badger\TagBundle\Taggable\TaggableInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Badge entity interface
 *
 * @author  Pierre Allard <pierre.allard@akeneo.com>
 * @license http://opensource.org/licenses/MIT The MIT License (MIT)
 */
interface BadgeInterface extends TaggableInterface
{
    /**
     * @return string
     */
    public function getId();

    /**
     * @return string
     */
    public function getTitle();

    /**
     * @param string $title
     *
     * @return $this
     */
    public function setTitle($title);

    /**
     * @return string
     */
    public function getDescription();

    /**
     * @param string $description
     *
     * @return $this
     */
    public function setDescription($description);

    /**
     * @return string
     */
    public function getImagePath();

    /**
     * @param string $imagePath
     *
     * @return $this
     */
    public function setImagePath($imagePath);

    /**
     * @return string|null
     */
    public function getImageAbsolutePath();

    /**
     * @return string|null
     */
    public function getImageWebPath();

    /**
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null);

    /**
     * @return UploadedFile
     */
    public function getFile();

    /**
     * Uploads a file
     */
    public function upload();
}

src/Badger/Bundle/GameBundle/Resources/views/adventures.html.twig
{% extends '@Game/base.html.twig' %}

{% block body %}
    <!-- Grid -->
    <div class="row">
        <div class="col-md-10 col-md-offset-1">

            <div class="tabbable">
                <ul class="nav nav-tabs nav-tabs-bottom nav-justified">
                    <li class="active"><a href="#available" data-toggle="tab">Available</a></li>
                    <li><a href="#completed" data-toggle="tab">Completed</a></li>
                </ul>

                <div class="tab-content">
                    <div class="tab-pane active" id="available">
                        {% if availableAdventures is empty %}
                            <div class="panel">
                                <div class="panel-body text-center">
                                    <div class="icon-object border-info-400 text-info"><i class="icon-trophy3"></i></div>
                                    <h5 class="text-semibold">No adventure available</h5>
                                    <p class="mb-15">There is no adventure available for now, come back later!</p>
                                </div>
                            </div>
                        {% else %}
                            <div class="panel panel-flat">
                                <ul class="media-list media-list-linked media-list-bordered">

                                    {% for adventure in availableAdventures %}
                                        <li class="media">
                                            <a href="{{ url('viewadventure', {id: adventure.id}) }}" class="media-link">
                                                <div class="media-left">
                                                    <span class="btn border-primary text-primary btn-flat btn-icon btn-rounded btn-sm"><i class="icon-trophy3"></i></span>
                                                </div>

                                                <div class="media-body">
                                                    <h6 class="media-heading text-semibold">{{ adventure.title }}</h6>

                                                    <div class="media-annotation mt-5">
                                                <span class="mr-10">
                                                    <i class="icon-medal2"></i> <b>{{ adventure.countAllBadges }}</b> <small>badges to unlock</small>
                                                </span>
                                                <span class="mr-10">
                                                    <i class="icon-piggy-bank"></i> <b>{{ adventure.countAllNuts }}</b> <small>nuts to win</small>
                                                </span>
                                                <span class="mr-10">
                                                    {% if adventure.isStepLinked %}
                                                        <i class="icon-link"></i> <small>steps are <b>ordered</b></small>
                                                    {% else %}
                                                        <i class="icon-link"></i> <small>steps are <b>not ordered</b></small>
                                                    {% endif %}
                                                </span>
                                                    </div>
                                                </div>

                                                <div class="media-right media-middle">
                                                    <span class="badge badge-primary">{{ adventure.completed }} / {{ adventure.steps|length }}</span>
                                                </div>
                                            </a>
                                        </li>
                                    {% endfor %}

                                </ul>
                            </div>
                        {% endif %}
                    </div>

                    <div class="tab-pane" id="completed">
                        {% if completedAdventures is empty %}
                            <div class="panel">
                                <div class="panel-body text-center">
                                    <div class="icon-object border-success-400 text-success"><i class="icon-stack-check"></i></div>
                                    <h5 class="text-semibold">No completed adventure</h5>
                                    <p class="mb-15">This tab will list all the adventures you have completed. Let's have some work!</p>
                                </div>
                            </div>
                        {% else %}
                            <div class="panel panel-flat">
                                <ul class="media-list media-list-linked media-list-bordered">

                                    {% for adventure in completedAdventures %}
                                        <li class="media">
                                            <a href="{{ url('viewadventure', {id: adventure.id}) }}" class="media-link">
                                                <div class="media-left">
                                                    <span class="btn border-success text-success btn-flat btn-icon btn-rounded btn-sm"><i class="icon-trophy3"></i></span>
                                                </div>

                                                <div class="media-body">
                                                    <h6 class="media-heading text-semibold">{{ adventure.title }}</h6>

                                                    <div class="media-annotation mt-5">
                                                <span class="mr-10">
                                                    <i class="icon-medal2"></i> <b>{{ adventure.countAllBadges }}</b> <small>badges unlocked</small>
                                                </span>
                                                <span class="mr-10">
                                                    <i class="icon-piggy-bank"></i> <b>{{ adventure.countAllNuts }}</b> <small>nuts won</small>
                                                </span>
                                                <span class="mr-10">
                                                    {% if adventure.isStepLinked %}
                                                        <i class="icon-link"></i> <small>steps are <b>ordered</b></small>
                                                    {% else %}
                                                        <i class="icon-link"></i> <small>steps are <b>not ordered</b></small>
                                                    {% endif %}
                                                </span>
                                                    </div>
                                                </div>
                                            </a>
                                        </li>
                                    {% endfor %}

                                </ul>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /grid -->
{% endblock %}

src/Badger/Bundle/GameBundle/Resources/views/badges.html.twig
{% extends '@Game/base.html.twig' %}

{% block body %}
    <div class="tabbable">
        <ul class="nav nav-tabs nav-tabs-bottom">
            {% for tag in tags %}
                {% if tag.badges is not empty %}
                <li class="{{ 1 == loop.index ? 'active' : ''}}"><a href="#{{ tag.code }}" data-toggle="tab">{{ tag.name }}</a></li>
                {% endif %}
            {% endfor %}
        </ul>

        <div class="tab-content">
            {% for tag in tags %}
                {% if tag.badges is not empty %}
                <div class="tab-pane {{ 1 == loop.index ? 'active' : ''}}" id="{{ tag.code }}">
                    <!-- Latest added -->
                    {% for row in tag.badges|batch(2) %}
                    <div class="row">

                        {% for badge in row %}
                        <div class="col-md-6">
                            {% if badge.id in unlockedBadgesIds %}
                            <div class="panel border-lg border-success" style="box-shadow: 0 0 15px -4px rgba(2,168,41,1);">
                            {% else %}
                            <div class="panel" style="opacity: 0.8;">
                            {% endif %}
                                <div class="panel-body">
                                    <div class="media">
                                        <div class="media-left">
                                            <a href="{{ url('viewbadge', {id: badge.id}) }}">
                                                <img style="width: 100px; height: 100px;" class="img-circle" src="{{ badge.imageWebPath }}" alt="">
                                            </a>
                                        </div>

                                        <div class="media-body">
                                            <h6 class="media-heading text-semibold">
                                                {% if badge.id in unlockedBadgesIds %}
                                                    <i class="icon-checkmark position-left text-success"></i>
                                                {% endif %}

                                                <a href="{{ url('viewbadge', {id: badge.id}) }}" class="text-default">{{ badge.title }}</a>
                                            </h6>
                                            <span class="description">
                                                {{ badge.description }}
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                    {% endfor %}
                    <!-- /latest added -->
                </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        // Auto link quests descriptions
        $('.description').each(function () {
            var linkedText = Autolinker.link( $(this).html() );
            $(this).html(linkedText);
        });
    </script>
{% endblock %}

src/Badger/Bundle/GameBundle/Resources/views/base-admin.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Badger{% endblock %}</title>
    <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>

    <!-- Global stylesheets -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
    <link href="{{ asset('bundles/game/css/icons/icomoon/styles.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('bundles/game/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('bundles/game/css/core.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('bundles/game/css/components.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('bundles/game/css/colors.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('bundles/game/css/extras/animate.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/badger.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('bundles/game/css/extras/selectize.bootstrap3.css') }}" rel="stylesheet" type="text/css">
    <!-- /global stylesheets -->

    <!-- Core JS files -->
    <script type="text/javascript" src="{{ asset('bundles/game/js/core/libraries/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('bundles/game/js/core/libraries/bootstrap.min.js') }}"></script>
    <!-- /core JS files -->

    <!-- Theme JS files -->
    <script type="text/javascript" src="{{ asset('bundles/game/js/plugins/ui/nicescroll.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('bundles/game/js/core/app.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('bundles/game/js/pages/layout_fixed_custom.js') }}"></script>
    <!-- /theme JS files -->

    <!-- Lib JS files -->
    <script type="text/javascript" src="{{ asset('vendor/dist/mustache.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('vendor/dist/lodash.min.js') }}"></script>
    <!-- /lib JS files -->

    {% block stylesheets %}{% endblock %}
    <link rel="icon" href="{{ asset('favicon.ico') }}" sizes="16x16 32x32 48x48 64x64" type="image/vnd.microsoft.icon">
</head>
<body class="{% block bodyclass %}{% endblock %} sidebar-xs">

<!-- Main navbar -->
<div class="navbar navbar-inverse">
    <div class="navbar-header">
        <a class="navbar-brand" href="{{ url('admin') }}"><img src="{{ asset('bundles/game/images/badger-white-300.png') }}" alt="" style="margin-top: -6px; height: 30px;"></a>

        <ul class="nav navbar-nav pull-right visible-xs-block">
            <li><a class="sidebar-mobile-main-toggle"><i class="icon-paragraph-justify3"></i></a></li>
        </ul>
    </div>
</div>
<!-- /main navbar -->

<!-- Page container -->
<div class="page-container">

    <!-- Page content -->
    <div class="page-content {% block pagecontentclass %}{% endblock %}">

        <!-- Main sidebar -->
        <div class="sidebar sidebar-main sidebar-default">
            <div class="sidebar-content">

                <!-- Main navigation -->
                <div class="sidebar-category sidebar-category-visible">
                    <div class="category-content no-padding">
                        <ul class="navigation navigation-main navigation-accordion">

                            <!-- Main -->
                            <li class="has-ul">
                                <a href="#"><i class="icon-medal2"></i> <span>Badges</span></a>

                                <ul class="hidden-ul">
                                    <li><a href="{{ url('admin_badge_index') }}"><i class="icon-list"></i> List</a></li>
                                    <li><a href="{{ url('admin_badge_new') }}"><i class="icon-plus2"></i> Create</a></li>
                                    <li><a href="{{ url('admin_claimed_badge_index') }}"><i class="icon-hour-glass2"></i> Pending</a></li>
                                    <li><a href="{{ url('admin_unlocked_badge_give') }}"><i class="icon-user-plus"></i> Give</a></li>
                                    <li><a href="{{ url('admin_unlocked_badge_remove') }}"><i class="icon-user-cancel"></i> Remove</a></li>
                                </ul>
                            </li>
                            <li class="has-ul">
                                <a href="#"><i class="icon-trophy4"></i> <span>Quests</span></a>

                                <ul class="hidden-ul">
                                    <li><a href="{{ url('admin_quest_index') }}"><i class="icon-list"></i> List</a></li>
                                    <li><a href="{{ url('admin_quest_new') }}"><i class="icon-plus2"></i> Create</a></li>
                                    <li><a href="{{ url('admin_claimed_quest_index') }}"><i class="icon-hour-glass2"></i> Pending</a></li>
                                </ul>
                            </li>
                            <li class="has-ul">
                                <a href="#"><i class="icon-trophy3"></i> <span>Adventures</span></a>

                                <ul class="hidden-ul">
                                    <li><a href="{{ url('admin_adventure_index') }}"><i class="icon-list"></i> List</a></li>
                                    <li><a href="{{ url('admin_adventure_form') }}"><i class="icon-plus2"></i> Create</a></li>
                                    <li><a href="{{ url('admin_claimed_adventure_step_index') }}"><i class="icon-hour-glass2"></i> Pending</a></li>
                                </ul>
                            </li>
                            <li class="has-ul">
                                <a href="#"><i class="icon-price-tag2"></i> <span>Tags</span></a>

                                <ul class="hidden-ul">
                                    <li><a href="{{ url('admin_tag_index') }}"><i class="icon-list"></i> List</a></li>
                                    <li><a href="{{ url('admin_tag_new') }}"><i class="icon-plus2"></i> Create</a></li>
                                </ul>
                            </li>
                            <li class="has-ul">
                                <a href="#"><i class="icon-users"></i> <span>People</span></a>

                                <ul class="hidden-ul">
                                    <li><a href="{{ url('admin_user_index') }}"><i class="icon-list"></i> List</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="{{ url('homepage') }}"><i class="icon-home2"></i> <span>Dashboard</span></a>
                            </li>
                            <!-- /main -->

                        </ul>
                    </div>
                </div>
                <!-- /main navigation -->

            </div>
        </div>
        <!-- /main sidebar -->


        <!-- Main content -->
        <div class="content-wrapper">

            <!-- Content area -->
            <div>


                <!-- Grid -->
                <div class="row">
                    <div class="col-md-12">
                        {% block body %}

                        {% endblock %}
                    </div>
                </div>
                <!-- /grid -->

            </div>
            <!-- /content area -->

        </div>
        <!-- /main content -->

    </div>
    <!-- /page content -->
</div>
<!-- /page container -->

<script src="{{ asset('vendor/dist/Autolinker.min.js') }}"></script>

{% block javascripts %}
{% endblock %}
</body>
</html>

src/Badger/Bundle/GameBundle/Resources/views/pending-votes.html.twig
{% extends '@Game/base.html.twig' %}

{% block body %}
    <div class="tabbable">
        <div class="tab-content">
            {% for item in votableItems %}
                    <div class="col-md-6">
                            <div class="panel-body">
                                <h6 class="media-heading text-semibold">{{ item.badgeCompletion.user.username|upper }} claimed the "{{ item.badgeCompletion.badge.title }}" badge, does he deserve it ?</h6>
                                <div class="media">
                                    <div class="media-left">
                                        <a href="{{ url('viewbadge', {id: item.badgeCompletion.badge.id}) }}">
                                            <img style="width: 100px; height: 100px;" class="img-circle img-thumbnail" src="{{ item.badgeCompletion.badge.imageWebPath }}" alt="">
                                        </a>
                                    </div>

                                    <div class="media-body">
                                        <h6 class="media-heading text-semibold">
                                            <a href="{{ url('viewbadge', {id: item.badgeCompletion.badge.id}) }}" class="text-default">{{ item.badgeCompletion.badge.title }}</a>
                                        </h6>
                                        <span class="description">
                                            {{ item.badgeCompletion.badge.description }}
                                        </span>
                                        <span class="vote">
                                            {{ votesResults[item.id] }}
                                        </span>
                                    </div>
                                </div>

                                    <div class="media-body">
                                        <a href="{{ url('badge_upvote', { 'id': item.id }) }}" class="btn btn-default btn-icon btn-rounded ml-10">
                                            <i class="icon-thumbs-up3"></i> Hell Yes !
                                        </a>

                                        <a href="{{ url('badge_downvote', { 'id': item.id }) }}" class="btn btn-default btn-icon btn-rounded ml-10">
                                            <i class="icon-thumbs-down3"></i> No, I'm a hater !
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            {% endfor %}
{% endblock %}

{% block javascripts %}
    <script>
        // Auto link quests descriptions
        $('.description').each(function () {
            var linkedText = Autolinker.link( $(this).html() );
            $(this).html(linkedText);
        });
    </script>
{% endblock %}

src/Badger/Bundle/GameBundle/Resources/views/user-profile.html.twig
{% extends '@Game/base.html.twig' %}

{% block body %}
    <!-- User profile -->
    <div class="row">
        <div class="col-lg-3">

            <!-- User thumbnail -->
            <div class="thumbnail">
                <div class="thumb thumb-rounded thumb-slide">
                    <img class="thumbnail" src="{{ user.profilePicture }}" alt="">
                </div>

                <div class="caption text-center">
                    <h6 class="text-semibold no-margin">{{ user.username }} <small class="display-block">{{ user.tags|join(', ') }}</small></h6>
                </div>
            </div>
            <!-- /user thumbnail -->


            <!-- Navigation -->
            <div class="panel panel-body no-padding-bottom">
                <div class="row text-center">
                    <div class="col-md-12">
                        <div class="content-group">
                            <h6 class="text-semibold no-margin"><i class="icon-medal2 position-left text-slate"></i> {{ badgeCompletions|length }}</h6>
                            <span class="text-muted text-size-small">BADGES</span>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /navigation -->
        </div>

        <div class="col-lg-9">
            <div class="tabbable">
                <ul class="nav nav-tabs nav-tabs-bottom">
                    <li class="active"><a href="#unlocked" data-toggle="tab" aria-expanded="true">Unlocked Badges <i class="icon-medal2 position-right"></i></a></li>
                </ul>

                <div class="tab-content">
                    <div class="tab-pane active" id="unlocked">
                        <!-- Latest added -->
                        {% for row in badgeCompletions|batch(2) %}
                        <div class="row">

                            {% for badgeCompletion in row %}
                            <div class="col-md-6">
                                <div class="panel">
                                    <div class="panel-body">
                                        <div class="media">
                                            <div class="media-left">
                                                <a href="{{ url('viewbadge', {id: badgeCompletion.badge.id}) }}"><img style="width: 100px; height: 100px;" class="img-circle" src="{{ badgeCompletion.badge.imageWebPath }}" alt=""></a>
                                            </div>

                                            <div class="media-body">
                                                <h6 class="media-heading text-semibold"><a href="{{ url('viewbadge', {id: badgeCompletion.badge.id}) }}" class="text-default">{{ badgeCompletion.badge.title }}</a></h6>
                                                {{ badgeCompletion.badge.description }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="panel-footer">
                                        <div class="heading-elements">
                                            <span class="heading-text text-muted"><i class="icon-checkmark position-left"></i> Unlocked on {{ badgeCompletion.completionDate|date("d/m/Y") }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}

                        </div>
                        {% endfor %}
                        <!-- /latest added -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /user profile -->
{% endblock %}

src/Badger/Bundle/GameBundle/Resources/views/view-badge.html.twig
{% extends '@Game/base.html.twig' %}

{% block body %}
    <!-- Grid -->
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            {% if isUnlocked %}
            <div class="panel border-lg border-success" style="margin-top: 50px; box-shadow: 0 0 15px -4px rgba(2,168,41,1);">
                <div class="panel-body text-center">
                    <img style="width: 150px; height: 150px; margin-top: -50px; box-shadow: 0px 0px 42px -12px rgba(0,0,0,0.75);" class="img-circle" src="{{ badge.imageWebPath }}" alt="">
                    <h5 class="text-semibold">{{ badge.title }}</h5>
                    <p class="mb-15 description">{{ badge.description }}</p>
                    <p class="text-muted"><i class="icon-checkmark position-left text-success"></i> You unlocked this badge</p>
                </div>
            </div>
            {% else %}
            <div class="panel" style="margin-top: 50px;">
                <div class="panel-body text-center">
                    <img style="width: 150px; height: 150px; margin-top: -50px; box-shadow: 0px 0px 42px -12px rgba(0,0,0,0.75);" class="img-circle" src="{{ badge.imageWebPath }}" alt="">
                    <h5 class="text-semibold">{{ badge.title }}</h5>
                    <p class="mb-15 description">{{ badge.description }}</p>
                    {% if not isClaimed %}
                    <button type="button" class="ml-10 btn bg-warning-400 btn-ladda btn-ladda-spinner heading-btn claim" data-style="expand-right" data-spinner-color="#333" data-spinner-size="20">
                        <span class="ladda-label">Claim this badge</span><span class="ladda-spinner"></span>
                    </button>
                    {% else %}
                        <span class="heading-text text-semibold text-muted">
                            <i class="icon-hour-glass"></i> You claimed this badge, waiting for validation
                        </span>
                    {% endif %}
                </div>
            </div>
            {% endif %}
        </div>
        <div class="col-md-12">
            <div class="text-center content-group text-muted content-divider">
                <span class="pt-10 pb-10"><i class="icon-users"></i> People who have this badge</span>
            </div>

            {% for row in badgeCompletions|batch(4) %}
                <div class="row">

                    {% for badgeCompletion in row %}
                        <div class="col-lg-3 col-md-6">
                            <div class="panel panel-body">
                                <div class="media">
                                    <div class="media-left">
                                        <a href="{{ url('userprofile', {'username': badgeCompletion.user.username}) }}" data-popup="lightbox">
                                            <img src="{{ badgeCompletion.user.profilePicture }}" class="img-circle img-lg" alt="">
                                        </a>
                                    </div>

                                    <div class="media-body">
                                        <h6 class="media-heading"><a class="text-default" href="{{ url('userprofile', {'username': badgeCompletion.user.username}) }}">{{ badgeCompletion.user.username }}</a></h6>
                                        <span class="text-muted">
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>
            {% endfor %}
        </div>
    </div>
    <!-- /grid -->
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('bundles/game/js/plugins/buttons/spin.min.js') }}"></script>
    <script src="{{ asset('bundles/game/js/plugins/buttons/ladda.min.js') }}"></script>

    <script>
        // Auto link quests descriptions
        $('.description').each(function () {
            var linkedText = Autolinker.link( $(this).html() );
            $(this).html(linkedText);
        });

        {% if not isUnlocked and not isClaimed %}
            $button = $('.claim');
            $button.click(function() {
                // Create a new instance of ladda for the specified button
                var l = Ladda.create( $(this)[0] );

                if ($(this).prop('disabled')) {
                    return;
                }

                l.start();

                $.post('{{ url('claimbadge', {'id': badge.id}) }}').then(function() {
                    l.stop();
                    $(this).html('<i class="icon-checkmark"></i> Claimed').prop('disabled', true);
                }.bind(this), function () {
                    l.stop();
                    $(this).html('<i class="icon-warning"></i> An error occured, click again to retry');
                }.bind(this));
            });
        {% endif %}
    </script>
{% endblock %}